#!/bin/bash

# Create a virtual machine with docker-machine using the virtualbox driver,
# and named Char.

docker-machine create --driver virtualbox --virtualbox-no-vtx-check Char

# --virtualbox-no-vtx-check add because of vtx issues on my machine