#!/bin/bash

# Create another virtual machine with docker-machine using the virtualbox
# driver, and name it Aiur.

docker-machine create --driver virtualbox --virtualbox-no-vtx-check Aiur

# --virtualbox-no-vtx-check add because of vtx issues on my machine